services:
  payments_postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - payments_postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  
  payments_api:
    build:
      context: ./PaymentsServer
      dockerfile: PaymentsServer.Presentation/Dockerfile
    image: payments_service_api:latest
    restart: always
    depends_on:
      - payments_postgres
    env_file:
      - ./.env
    environment:
      - ConnectionStrings__Postgres=${ConnectionStrings__Postgres}

    ports:
      - "6000:5002"
    networks:
      - backend
    

networks:
  backend:
    driver: bridge
    
volumes:
  payments_postgres_data:
  
  